# docker run -d \
#   --name kali \
#   --restart unless-stopped \
#   -p 3011:3000 \
#   -p 3009:3001 \
#   --security-opt seccomp=unconfined \
#   -e PUID=1000 \
#   -e PGID=1000 \
#   -e TZ=Asia/Karachi \
#   -e SUBFOLDER=/ \
#   -e TITLE="Kali Linux" \
#   -e USERNAME=kali \
#   -e PASSWORD=kali \
#   --device /dev/dri:/dev/dri \
#   --shm-size="1gb" \
#   lscr.io/linuxserver/kali-linux:latest

services:
  kali:
    image: lscr.io/linuxserver/kali-linux:latest
    container_name: kali
    restart: unless-stopped
    ports:
      - "3011:3000"
      - "3009:3001"
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Asia/Karachi
      - SUBFOLDER=/
      - TITLE=Kali Linux
      - USERNAME=kali
      - PASSWORD=kali
    security_opt:
      - seccomp=unconfined
    devices:
      - /dev/dri:/dev/dri
    shm_size: "1gb"
