# docker compose -f ./kali.compose.yaml up -d
# docker compose -f ./kali.compose.yaml logs
# version: '3.8'

services:
  kali-desktop:
    image: kasmweb/kali-rolling-desktop:1.16.0
    container_name: kali-rolling-desktop
    shm_size: 512m
    ports:
      - "6901:6901"
    environment:
      - VNC_PW=password
    stdin_open: true
    tty: true
    restart: unless-stopped
    networks:
      - default

networks:
  default:
    driver: bridge