Vagrant.configure("2") do |config|
  config.vm.box = "kalilinux/rolling"

  config.vm.provider "virtualbox" do |vb|
    vb.memory = "2048"  # 2 GB of RAM
    vb.cpus = 2         # 2 CPU cores
  end

  config.vm.network "public_network"  # Bridged network mode
  config.vm.network "forwarded_port", guest: 5901, host: 5901  # VNC on port 5901
  config.vm.synced_folder "~/.openvpn", "/home/vagrant/.openvpn"

  config.vm.provision "shell", inline: <<-SHELL
    apt-get update
    apt-get install -y tightvncserver
    chown -R vagrant:vagrant /home/vagrant/.openvpn
    tightvncserver :1
  SHELL
end
