# provision.yml
---
- hosts: kali
  become: yes

  tasks:
    - name: Update apt package list
      apt:
        update_cache: yes

    - name: Install required packages for Docker
      apt:
        name:
          - apt-transport-https
          - ca-certificates
          - curl
          - gnupg-agent
          - software-properties-common
        state: present